name: Contexts demo
on:
  push:
    branches: [ "main" ]

env:
  project: "roboshop"
  component: "catalogue"
  environment: "dev"
jobs:
  github-context:
    runs-on: ubuntu-latest
    steps:
      - name: access env variables
        run: |
          echo "Project: $project"
          echo "Component: $component"
          echo "Environment: $environment"

      - name: print context
        run: |
          echo "${{ toJson(github) }}"
          echo "branch name: ${{ github.ref_name }}"
